### ISSUE TITLE
IP address anonymization possible?

### ISSUE THREAD

**Issue by hyperknot** [bd808/python-iptools#21]
Is it possible to use this library to parse IPv4 and IPv6 addresses and anonymize them like Google Analytics does?

That is:

> The IP anonymization feature in Analytics sets the last octet of IPv4 user IP addresses and the last 80 bits of IPv6 addresses to zeros

> For example, an IP address of 12.214.31.144 would be changed to 12.214.31.0. (If the IP address is an IPv6 address, the last 80 of the 128 bits are set to zero.) 

  [1]: https://support.google.com/analytics/answer/2763052?hl=en

**Comment by bd808** [comment]
bitwise AND should do it:
```
>>> from iptools import ipv4, ipv6
>>> ipv4.long2ip(ipv4.ip2long('12.214.31.144') & ipv4.ip2long('255.255.255.0'))
'12.214.31.0'
>>> ipv6.long2ip(ipv6.ip2long('2607:f8b0:400e:c08::8b') & ipv6.ip2long('ffff:ffff:ffff::'))
'2607:f8b0:400e::'
```
